# frozen_string_literal: true

require "rails_helper"

RSpec.describe Deploy::ContentDiff do
  def schema = "content_diff_spec"

  def probe = "content_diff_probe"

  def url
    config = ActiveRecord::Base.connection_db_config.configuration_hash
    "postgres://#{config[:host] || "localhost"}:#{config[:port] || 5432}/#{config[:database]}"
  end

  let(:table) { Deploy::ContentTables::Table.new(name: probe, key: %w[id], scope: nil, surrogate: false) }
  let(:natural) {
    Deploy::ContentTables::Table.new(name: probe, key: %w[sentence_id lexeme_id], scope: nil, surrogate: true)
  }
  let(:source) { described_class.connect(url).tap { |c| c.exec("SET search_path = #{schema}, public") } }
  let(:target) { described_class.connect(url).tap { |c| c.exec("SET client_min_messages = warning") } }
  let(:diff) { described_class.new(source:, target:) }

  before do
    target.exec(
      <<~SQL
        DROP SCHEMA IF EXISTS #{schema} CASCADE;
        DROP TABLE IF EXISTS public.#{probe};
        DROP TABLE IF EXISTS public.#{probe}_parent;
        CREATE TABLE public.#{probe}_parent (id bigint PRIMARY KEY);
        INSERT INTO public.#{probe}_parent VALUES (10), (11), (12), (99);
        CREATE TABLE public.#{probe} (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          sentence_id bigint NOT NULL REFERENCES public.#{probe}_parent (id),
          lexeme_id bigint NOT NULL,
          slot integer,
          score float8,
          data jsonb NOT NULL DEFAULT '{}',
          tags integer[] NOT NULL DEFAULT '{}',
          note text,
          updated_at timestamp(6) NOT NULL DEFAULT now(),
          code text,
          UNIQUE (sentence_id, lexeme_id),
          UNIQUE (slot),
          UNIQUE (code)
        );
        CREATE SCHEMA #{schema};
        CREATE TABLE #{schema}.#{probe} (LIKE public.#{probe} INCLUDING ALL);
      SQL
    )
  end

  after do
    source.close
    target.exec(
      "DROP SCHEMA IF EXISTS #{schema} CASCADE; DROP TABLE IF EXISTS public.#{probe}; DROP TABLE IF EXISTS public.#{probe}_parent"
    )
    target.close
  end

  def seed(connection, rows)
    rows.each do |id, sentence, lexeme, slot, score, data, tags, note|
      connection.exec_params(
        "INSERT INTO #{probe} (id, sentence_id, lexeme_id, slot, score, data, tags, note, updated_at) " \
          "VALUES ($1, $2, $3, $4, $5, $6, $7, $8, '2026-09-08 10:00:00')",
        [id, sentence, lexeme, slot, score, data, tags, note]
      )
    end
  end

  def rows(connection)
    connection
      .exec("SELECT id, sentence_id, lexeme_id, slot, score, data, tags, note, code FROM #{probe} ORDER BY id")
      .values
  end

  let(:base) do
    [
      [1, 10, 100, 1, 0.5, "{\"a\": 1}", "{1,2}", "plain"],
      [2, 10, 101, 2, nil, "{}", "{}", "tab\there\nnewline\\slash"],
      [3, 11, 100, 3, 1.0e-7, "{\"nested\": {\"b\": [1, 2]}}", "{3}", nil]
    ]
  end

  it "finds nothing to do when both sides hold the same rows" do
    seed(source, base)
    seed(target, base)

    expect(diff.plan(table)).to(be_empty)
    expect(diff.digest(source, table)).to(eq(diff.digest(target, table)))
  end

  it "carries inserts, updates and deletes across and verifies the result" do
    seed(source, base + [[4, 12, 100, 4, 2.5, "{}", "{}", "new"]])
    seed(
      target,
      base.first(2) +
        [
          [3, 11, 100, 3, 1.0e-7, "{\"nested\": {\"b\": [1, 2]}}", "{3}", "stale"],
          [9, 99, 99, 9, nil, "{}", "{}", "gone"]
        ]
    )

    plan = diff.plan(table)

    expect(plan.inserts).to(eq([[4]]))
    expect(plan.updates).to(eq([[3]]))
    expect(plan.deletes).to(eq([[9]]))

    target.transaction do
      diff.delete(table, plan.deletes)
      expect(diff.apply(plan.with(deletes: []))).to(eq(inserted: 1, updated: 1, deleted: 0))
      diff.verify!(table)
    end

    expect(rows(target)).to(eq(rows(source)))
    expect(target.exec("SELECT note FROM #{probe} WHERE id = 2").getvalue(0, 0)).to(eq("tab\there\nnewline\\slash"))
  end

  it "ignores timestamps on their own but carries them along with a real change" do
    seed(source, base)
    seed(target, base)
    source.exec("UPDATE #{probe} SET updated_at = '2026-09-09 12:00:00'")

    expect(diff.plan(table)).to(be_empty)

    source.exec("UPDATE #{probe} SET note = 'edited' WHERE id = 1")
    target.transaction { diff.apply(diff.plan(table)) }

    expect(target.exec("SELECT note, updated_at FROM #{probe} WHERE id = 1").values).to(
      eq([["edited", "2026-09-09 12:00:00"]])
    )
    expect(target.exec("SELECT updated_at FROM #{probe} WHERE id = 2").getvalue(0, 0)).to(eq("2026-09-08 10:00:00"))
  end

  it "treats a null and an empty string as different values" do
    seed(source, [[1, 10, 100, 1, nil, "{}", "{}", ""]])
    seed(target, [[1, 10, 100, 1, nil, "{}", "{}", nil]])

    expect(diff.plan(table).updates).to(eq([[1]]))
  end

  it "compares a surrogate table on its natural key and leaves the target ids alone" do
    seed(source, [[50, 10, 100, 1, 0.5, "{}", "{}", "same"], [51, 10, 101, 2, 0.5, "{}", "{}", "changed"]])
    seed(
      target,
      [
        [1, 10, 100, 1, 0.5, "{}", "{}", "same"],
        [2, 10, 101, 2, 0.5, "{}", "{}", "old"],
        [3, 10, 102, 3, nil, "{}", "{}", "extra"]
      ]
    )

    plan = diff.plan(natural)

    expect(plan.inserts).to(be_empty)
    expect(plan.updates).to(eq([[10, 101]]))
    expect(plan.deletes).to(eq([[10, 102]]))

    target.transaction do
      diff.delete(natural, plan.deletes)
      diff.apply(plan.with(deletes: []))
      diff.verify!(natural)
    end

    expect(target.exec("SELECT id, note FROM #{probe} ORDER BY id").values).to(eq([["1", "same"], ["2", "changed"]]))
  end

  it "parks colliding rows so a swap on a unique integer column still goes through" do
    seed(source, [[1, 10, 100, 2, nil, "{}", "{}", "a"], [2, 10, 101, 1, nil, "{}", "{}", "b"]])
    seed(target, [[1, 10, 100, 1, nil, "{}", "{}", "a"], [2, 10, 101, 2, nil, "{}", "{}", "b"]])

    plan = diff.plan(table)
    expect(plan.updates).to(match_array([[1], [2]]))

    target.transaction do
      diff.apply(plan)
      diff.verify!(table)
    end

    expect(target.exec("SELECT id, slot FROM #{probe} ORDER BY id").values).to(eq([["1", "2"], ["2", "1"]]))
  end

  it "parks colliding rows on a unique text column too" do
    seed(source, [[1, 10, 100, 1, nil, "{}", "{}", "a"], [2, 10, 101, 2, nil, "{}", "{}", "b"]])
    seed(target, [[1, 10, 100, 1, nil, "{}", "{}", "a"], [2, 10, 101, 2, nil, "{}", "{}", "b"]])
    source.exec("UPDATE #{probe} SET code = CASE id WHEN 1 THEN 'second' ELSE 'first' END")
    target.exec("UPDATE #{probe} SET code = CASE id WHEN 1 THEN 'first' ELSE 'second' END")

    target.transaction do
      diff.apply(diff.plan(table))
      diff.verify!(table)
    end

    expect(target.exec("SELECT id, code FROM #{probe} ORDER BY id").values).to(eq([["1", "second"], ["2", "first"]]))
  end

  it "never parks a foreign key column, so a swap under a referencing unique index still goes through" do
    seed(source, [[1, 10, 101, 1, nil, "{}", "{}", "a"], [2, 10, 100, 2, nil, "{}", "{}", "b"]])
    seed(target, [[1, 10, 100, 1, nil, "{}", "{}", "a"], [2, 10, 101, 2, nil, "{}", "{}", "b"]])

    target.transaction do
      diff.apply(diff.plan(table))
      diff.verify!(table)
    end

    expect(target.exec("SELECT id, sentence_id, lexeme_id FROM #{probe} ORDER BY id").values).to(
      eq([["1", "10", "101"], ["2", "10", "100"]])
    )
  end

  it "applies a plan in batches and still parks a swap whose two rows land in different batches" do
    stub_const("Deploy::ContentDiff::APPLY_BATCH", 1)
    seed(
      source,
      [
        [1, 10, 100, 2, nil, "{}", "{}", "a"],
        [2, 10, 101, 1, nil, "{}", "{}", "b"],
        [3, 11, 100, 3, 0.5, "{}", "{}", "c"]
      ]
    )
    seed(target, [[1, 10, 100, 1, nil, "{}", "{}", "a"], [2, 10, 101, 2, nil, "{}", "{}", "b"]])

    plan = diff.plan(table)

    target.transaction do
      expect(diff.apply(plan)).to(eq(inserted: 1, updated: 2, deleted: 0))
      diff.verify!(table)
    end

    expect(target.exec("SELECT id, slot FROM #{probe} ORDER BY id").values).to(eq([["1", "2"], ["2", "1"], ["3", "3"]]))
  end

  it "moves every updated row before inserting, so a new row may take a value an older row gives up" do
    stub_const("Deploy::ContentDiff::APPLY_BATCH", 1)
    seed(source, [[1, 10, 100, 9, nil, "{}", "{}", "a"], [2, 10, 101, 1, nil, "{}", "{}", "new"]])
    seed(target, [[1, 10, 100, 1, nil, "{}", "{}", "a"]])

    target.transaction do
      expect(diff.apply(diff.plan(table))).to(eq(inserted: 1, updated: 1, deleted: 0))
      diff.verify!(table)
    end

    expect(target.exec("SELECT id, slot FROM #{probe} ORDER BY id").values).to(eq([["1", "9"], ["2", "1"]]))
  end

  it "opens every connection with enough temporary buffers for read-ahead to leave room for TOAST" do
    connection = described_class.connect(url)

    expect(connection.exec("SHOW temp_buffers").getvalue(0, 0)).to(eq(described_class::TEMP_BUFFERS))
  ensure
    connection&.close
  end

  it "refuses to park a column that already holds negative values" do
    seed(source, [[1, 10, 100, -1, nil, "{}", "{}", "a"], [2, 10, 101, -2, nil, "{}", "{}", "b"]])
    seed(target, [[1, 10, 100, -2, nil, "{}", "{}", "a"], [2, 10, 101, -1, nil, "{}", "{}", "b"]])

    expect { target.transaction { diff.apply(diff.plan(table)) } }.to(
      raise_error(described_class::Mismatch, /negative/)
    )
  end

  it "raises instead of committing when the target still differs" do
    seed(source, base)
    seed(target, base.first(2))

    expect { diff.verify!(table) }.to(raise_error(described_class::Mismatch, /#{probe}/))
  end

  it "copies the sequence state so both sides hand out the same next id" do
    seed(source, base)
    source.exec("SELECT setval(pg_get_serial_sequence('#{probe}', 'id'), 777, true)")

    diff.copy_sequences([table])

    expect(target.exec("SELECT nextval(pg_get_serial_sequence('#{probe}', 'id'))").getvalue(0, 0)).to(eq("778"))
  end

  it "refuses to work across databases whose columns disagree" do
    target.exec("ALTER TABLE public.#{probe} ADD COLUMN extra text")

    expect { diff.columns(table) }.to(raise_error(described_class::Mismatch, /columns differ/))
  end
end
