pin("application")
pin("@hotwired/turbo-rails", to: "turbo.min.js")
pin("@hotwired/stimulus", to: "stimulus.min.js")
pin("@hotwired/stimulus-loading", to: "stimulus-loading.js")
pin_all_from("app/javascript/controllers", under: "controllers")
pin("hanzi-writer", to: "hanzi-writer.min.js")
pin("hanzi-lookup", to: "hanzilookup.min.js")
pin("@floating-ui/dom", to: "@floating-ui--dom.js")
pin("@floating-ui/core", to: "@floating-ui--core.js")
pin("@floating-ui/utils", to: "@floating-ui--utils.js")
pin("@floating-ui/utils/dom", to: "@floating-ui--utils--dom.js")
